[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solpot = "22tsqvygTkEoomxNduhqEPYKA3DXfPPzNLXVxv9DAp8A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/solpot-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
